// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto
// Protobuf C++ Version: 5.26.1

#include "server.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace signaling {

inline constexpr Message::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        meth_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        userid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        password_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        from_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        to_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        call_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        sdp_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        signal_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        reason_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        cmeth_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        isresponse_{false},
        cseq_{0},
        statuscode_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Message::Message(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MessageDefaultTypeInternal() {}
  union {
    Message _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MessageDefaultTypeInternal _Message_default_instance_;
}  // namespace signaling
static ::_pb::Metadata file_level_metadata_server_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_server_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_server_2eproto = nullptr;
const ::uint32_t
    TableStruct_server_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::signaling::Message, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::signaling::Message, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::signaling::Message, _impl_.meth_),
        PROTOBUF_FIELD_OFFSET(::signaling::Message, _impl_.isresponse_),
        PROTOBUF_FIELD_OFFSET(::signaling::Message, _impl_.userid_),
        PROTOBUF_FIELD_OFFSET(::signaling::Message, _impl_.password_),
        PROTOBUF_FIELD_OFFSET(::signaling::Message, _impl_.from_),
        PROTOBUF_FIELD_OFFSET(::signaling::Message, _impl_.to_),
        PROTOBUF_FIELD_OFFSET(::signaling::Message, _impl_.cseq_),
        PROTOBUF_FIELD_OFFSET(::signaling::Message, _impl_.call_id_),
        PROTOBUF_FIELD_OFFSET(::signaling::Message, _impl_.sdp_),
        PROTOBUF_FIELD_OFFSET(::signaling::Message, _impl_.signal_),
        PROTOBUF_FIELD_OFFSET(::signaling::Message, _impl_.reason_),
        PROTOBUF_FIELD_OFFSET(::signaling::Message, _impl_.cmeth_),
        PROTOBUF_FIELD_OFFSET(::signaling::Message, _impl_.statuscode_),
        ~0u,
        ~0u,
        0,
        1,
        2,
        3,
        ~0u,
        4,
        5,
        6,
        7,
        8,
        9,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 21, -1, sizeof(::signaling::Message)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::signaling::_Message_default_instance_._instance,
};
const char descriptor_table_protodef_server_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014server.proto\022\tsignaling\"\363\002\n\007Message\022\014\n"
    "\004meth\030\001 \001(\t\022\022\n\nisResponse\030\002 \001(\010\022\023\n\006userI"
    "d\030\003 \001(\tH\000\210\001\001\022\025\n\010password\030\004 \001(\tH\001\210\001\001\022\021\n\004F"
    "rom\030\005 \001(\tH\002\210\001\001\022\017\n\002To\030\006 \001(\tH\003\210\001\001\022\014\n\004Cseq\030"
    "\007 \001(\005\022\024\n\007Call_ID\030\010 \001(\tH\004\210\001\001\022\020\n\003SDP\030\t \001(\t"
    "H\005\210\001\001\022\023\n\006signal\030\n \001(\tH\006\210\001\001\022\023\n\006reason\030\013 \001"
    "(\tH\007\210\001\001\022\022\n\005Cmeth\030\014 \001(\tH\010\210\001\001\022\027\n\nstatusCod"
    "e\030\r \001(\005H\t\210\001\001B\t\n\007_userIdB\013\n\t_passwordB\007\n\005"
    "_FromB\005\n\003_ToB\n\n\010_Call_IDB\006\n\004_SDPB\t\n\007_sig"
    "nalB\t\n\007_reasonB\010\n\006_CmethB\r\n\013_statusCode2"
    "O\n\020SignalingService\022;\n\013MessageCall\022\022.sig"
    "naling.Message\032\022.signaling.Message\"\000(\0010\001"
    "b\006proto3"
};
static ::absl::once_flag descriptor_table_server_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_server_2eproto = {
    false,
    false,
    488,
    descriptor_table_protodef_server_2eproto,
    "server.proto",
    &descriptor_table_server_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_server_2eproto::offsets,
    file_level_metadata_server_2eproto,
    file_level_enum_descriptors_server_2eproto,
    file_level_service_descriptors_server_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_server_2eproto_getter() {
  return &descriptor_table_server_2eproto;
}
namespace signaling {
// ===================================================================

class Message::_Internal {
 public:
  using HasBits = decltype(std::declval<Message>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(Message, _impl_._has_bits_);
};

Message::Message(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:signaling.Message)
}
inline PROTOBUF_NDEBUG_INLINE Message::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        meth_(arena, from.meth_),
        userid_(arena, from.userid_),
        password_(arena, from.password_),
        from_(arena, from.from_),
        to_(arena, from.to_),
        call_id_(arena, from.call_id_),
        sdp_(arena, from.sdp_),
        signal_(arena, from.signal_),
        reason_(arena, from.reason_),
        cmeth_(arena, from.cmeth_) {}

Message::Message(
    ::google::protobuf::Arena* arena,
    const Message& from)
    : ::google::protobuf::Message(arena) {
  Message* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, isresponse_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, isresponse_),
           offsetof(Impl_, statuscode_) -
               offsetof(Impl_, isresponse_) +
               sizeof(Impl_::statuscode_));

  // @@protoc_insertion_point(copy_constructor:signaling.Message)
}
inline PROTOBUF_NDEBUG_INLINE Message::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        meth_(arena),
        userid_(arena),
        password_(arena),
        from_(arena),
        to_(arena),
        call_id_(arena),
        sdp_(arena),
        signal_(arena),
        reason_(arena),
        cmeth_(arena) {}

inline void Message::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, isresponse_),
           0,
           offsetof(Impl_, statuscode_) -
               offsetof(Impl_, isresponse_) +
               sizeof(Impl_::statuscode_));
}
Message::~Message() {
  // @@protoc_insertion_point(destructor:signaling.Message)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Message::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.meth_.Destroy();
  _impl_.userid_.Destroy();
  _impl_.password_.Destroy();
  _impl_.from_.Destroy();
  _impl_.to_.Destroy();
  _impl_.call_id_.Destroy();
  _impl_.sdp_.Destroy();
  _impl_.signal_.Destroy();
  _impl_.reason_.Destroy();
  _impl_.cmeth_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Message::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(Message, _impl_._cached_size_),
              false,
          },
          &Message::MergeImpl,
          &Message::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void Message::Clear() {
// @@protoc_insertion_point(message_clear_start:signaling.Message)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.meth_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.userid_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.password_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.from_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000008u) {
      _impl_.to_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000010u) {
      _impl_.call_id_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000020u) {
      _impl_.sdp_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000040u) {
      _impl_.signal_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000080u) {
      _impl_.reason_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x00000100u) {
    _impl_.cmeth_.ClearNonDefaultToEmpty();
  }
  ::memset(&_impl_.isresponse_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.cseq_) -
      reinterpret_cast<char*>(&_impl_.isresponse_)) + sizeof(_impl_.cseq_));
  _impl_.statuscode_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Message::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 13, 0, 85, 2> Message::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Message, _impl_._has_bits_),
    0, // no _extensions_
    13, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294959104,  // skipmap
    offsetof(decltype(_table_), field_entries),
    13,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Message_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::signaling::Message>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string meth = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Message, _impl_.meth_)}},
    // bool isResponse = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Message, _impl_.isresponse_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Message, _impl_.isresponse_)}},
    // optional string userId = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(Message, _impl_.userid_)}},
    // optional string password = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 1, 0, PROTOBUF_FIELD_OFFSET(Message, _impl_.password_)}},
    // optional string From = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 2, 0, PROTOBUF_FIELD_OFFSET(Message, _impl_.from_)}},
    // optional string To = 6;
    {::_pbi::TcParser::FastUS1,
     {50, 3, 0, PROTOBUF_FIELD_OFFSET(Message, _impl_.to_)}},
    // int32 Cseq = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Message, _impl_.cseq_), 63>(),
     {56, 63, 0, PROTOBUF_FIELD_OFFSET(Message, _impl_.cseq_)}},
    // optional string Call_ID = 8;
    {::_pbi::TcParser::FastUS1,
     {66, 4, 0, PROTOBUF_FIELD_OFFSET(Message, _impl_.call_id_)}},
    // optional string SDP = 9;
    {::_pbi::TcParser::FastUS1,
     {74, 5, 0, PROTOBUF_FIELD_OFFSET(Message, _impl_.sdp_)}},
    // optional string signal = 10;
    {::_pbi::TcParser::FastUS1,
     {82, 6, 0, PROTOBUF_FIELD_OFFSET(Message, _impl_.signal_)}},
    // optional string reason = 11;
    {::_pbi::TcParser::FastUS1,
     {90, 7, 0, PROTOBUF_FIELD_OFFSET(Message, _impl_.reason_)}},
    // optional string Cmeth = 12;
    {::_pbi::TcParser::FastUS1,
     {98, 8, 0, PROTOBUF_FIELD_OFFSET(Message, _impl_.cmeth_)}},
    // optional int32 statusCode = 13;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Message, _impl_.statuscode_), 9>(),
     {104, 9, 0, PROTOBUF_FIELD_OFFSET(Message, _impl_.statuscode_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string meth = 1;
    {PROTOBUF_FIELD_OFFSET(Message, _impl_.meth_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool isResponse = 2;
    {PROTOBUF_FIELD_OFFSET(Message, _impl_.isresponse_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // optional string userId = 3;
    {PROTOBUF_FIELD_OFFSET(Message, _impl_.userid_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string password = 4;
    {PROTOBUF_FIELD_OFFSET(Message, _impl_.password_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string From = 5;
    {PROTOBUF_FIELD_OFFSET(Message, _impl_.from_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string To = 6;
    {PROTOBUF_FIELD_OFFSET(Message, _impl_.to_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 Cseq = 7;
    {PROTOBUF_FIELD_OFFSET(Message, _impl_.cseq_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // optional string Call_ID = 8;
    {PROTOBUF_FIELD_OFFSET(Message, _impl_.call_id_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string SDP = 9;
    {PROTOBUF_FIELD_OFFSET(Message, _impl_.sdp_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string signal = 10;
    {PROTOBUF_FIELD_OFFSET(Message, _impl_.signal_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string reason = 11;
    {PROTOBUF_FIELD_OFFSET(Message, _impl_.reason_), _Internal::kHasBitsOffset + 7, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string Cmeth = 12;
    {PROTOBUF_FIELD_OFFSET(Message, _impl_.cmeth_), _Internal::kHasBitsOffset + 8, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional int32 statusCode = 13;
    {PROTOBUF_FIELD_OFFSET(Message, _impl_.statuscode_), _Internal::kHasBitsOffset + 9, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\21\4\0\6\10\4\2\0\7\3\6\6\5\0\0\0"
    "signaling.Message"
    "meth"
    "userId"
    "password"
    "From"
    "To"
    "Call_ID"
    "SDP"
    "signal"
    "reason"
    "Cmeth"
  }},
};

::uint8_t* Message::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:signaling.Message)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string meth = 1;
  if (!this->_internal_meth().empty()) {
    const std::string& _s = this->_internal_meth();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "signaling.Message.meth");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // bool isResponse = 2;
  if (this->_internal_isresponse() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this->_internal_isresponse(), target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // optional string userId = 3;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_userid();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "signaling.Message.userId");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // optional string password = 4;
  if (cached_has_bits & 0x00000002u) {
    const std::string& _s = this->_internal_password();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "signaling.Message.password");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // optional string From = 5;
  if (cached_has_bits & 0x00000004u) {
    const std::string& _s = this->_internal_from();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "signaling.Message.From");
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  // optional string To = 6;
  if (cached_has_bits & 0x00000008u) {
    const std::string& _s = this->_internal_to();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "signaling.Message.To");
    target = stream->WriteStringMaybeAliased(6, _s, target);
  }

  // int32 Cseq = 7;
  if (this->_internal_cseq() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<7>(
            stream, this->_internal_cseq(), target);
  }

  // optional string Call_ID = 8;
  if (cached_has_bits & 0x00000010u) {
    const std::string& _s = this->_internal_call_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "signaling.Message.Call_ID");
    target = stream->WriteStringMaybeAliased(8, _s, target);
  }

  // optional string SDP = 9;
  if (cached_has_bits & 0x00000020u) {
    const std::string& _s = this->_internal_sdp();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "signaling.Message.SDP");
    target = stream->WriteStringMaybeAliased(9, _s, target);
  }

  // optional string signal = 10;
  if (cached_has_bits & 0x00000040u) {
    const std::string& _s = this->_internal_signal();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "signaling.Message.signal");
    target = stream->WriteStringMaybeAliased(10, _s, target);
  }

  // optional string reason = 11;
  if (cached_has_bits & 0x00000080u) {
    const std::string& _s = this->_internal_reason();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "signaling.Message.reason");
    target = stream->WriteStringMaybeAliased(11, _s, target);
  }

  // optional string Cmeth = 12;
  if (cached_has_bits & 0x00000100u) {
    const std::string& _s = this->_internal_cmeth();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "signaling.Message.Cmeth");
    target = stream->WriteStringMaybeAliased(12, _s, target);
  }

  // optional int32 statusCode = 13;
  if (cached_has_bits & 0x00000200u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<13>(
            stream, this->_internal_statuscode(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:signaling.Message)
  return target;
}

::size_t Message::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:signaling.Message)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string meth = 1;
  if (!this->_internal_meth().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_meth());
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // optional string userId = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_userid());
    }

    // optional string password = 4;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_password());
    }

    // optional string From = 5;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_from());
    }

    // optional string To = 6;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_to());
    }

    // optional string Call_ID = 8;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_call_id());
    }

    // optional string SDP = 9;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_sdp());
    }

    // optional string signal = 10;
    if (cached_has_bits & 0x00000040u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_signal());
    }

    // optional string reason = 11;
    if (cached_has_bits & 0x00000080u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_reason());
    }

  }
  // optional string Cmeth = 12;
  if (cached_has_bits & 0x00000100u) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_cmeth());
  }

  // bool isResponse = 2;
  if (this->_internal_isresponse() != 0) {
    total_size += 2;
  }

  // int32 Cseq = 7;
  if (this->_internal_cseq() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_cseq());
  }

  // optional int32 statusCode = 13;
  if (cached_has_bits & 0x00000200u) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_statuscode());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Message::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Message*>(&to_msg);
  auto& from = static_cast<const Message&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:signaling.Message)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_meth().empty()) {
    _this->_internal_set_meth(from._internal_meth());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_userid(from._internal_userid());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_password(from._internal_password());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_from(from._internal_from());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_internal_set_to(from._internal_to());
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_internal_set_call_id(from._internal_call_id());
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_internal_set_sdp(from._internal_sdp());
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_internal_set_signal(from._internal_signal());
    }
    if (cached_has_bits & 0x00000080u) {
      _this->_internal_set_reason(from._internal_reason());
    }
  }
  if (cached_has_bits & 0x00000100u) {
    _this->_internal_set_cmeth(from._internal_cmeth());
  }
  if (from._internal_isresponse() != 0) {
    _this->_impl_.isresponse_ = from._impl_.isresponse_;
  }
  if (from._internal_cseq() != 0) {
    _this->_impl_.cseq_ = from._impl_.cseq_;
  }
  if (cached_has_bits & 0x00000200u) {
    _this->_impl_.statuscode_ = from._impl_.statuscode_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Message::CopyFrom(const Message& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:signaling.Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Message::IsInitialized() const {
  return true;
}

void Message::InternalSwap(Message* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.meth_, &other->_impl_.meth_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.userid_, &other->_impl_.userid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.password_, &other->_impl_.password_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.from_, &other->_impl_.from_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.to_, &other->_impl_.to_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.call_id_, &other->_impl_.call_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.sdp_, &other->_impl_.sdp_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.signal_, &other->_impl_.signal_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.reason_, &other->_impl_.reason_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.cmeth_, &other->_impl_.cmeth_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Message, _impl_.statuscode_)
      + sizeof(Message::_impl_.statuscode_)
      - PROTOBUF_FIELD_OFFSET(Message, _impl_.isresponse_)>(
          reinterpret_cast<char*>(&_impl_.isresponse_),
          reinterpret_cast<char*>(&other->_impl_.isresponse_));
}

::google::protobuf::Metadata Message::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_server_2eproto_getter,
                                   &descriptor_table_server_2eproto_once,
                                   file_level_metadata_server_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace signaling
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::std::false_type _static_init_ PROTOBUF_UNUSED =
    (::_pbi::AddDescriptors(&descriptor_table_server_2eproto),
     ::std::false_type{});
#include "google/protobuf/port_undef.inc"
