[this]
;用户名和密码
userId=3082
passwd=zzx       

[server]
num=4                            ;服务器地址数目
signling0=47.93.119.6:30140      ;J组信令服务器公网地址
signling1=47.93.119.6:30150      ;X组信令服务器公网地址
signling2=10.1.69.7:50505        ;J组信令服务器内网地址
signling3=10.1.29.247:32101      ;X组信令服务器内网地址