// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: server.proto

#include "server.pb.h"
#include "server.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace signaling {

static const char* SignalingService_method_names[] = {
  "/signaling.SignalingService/MessageCall",
};

std::unique_ptr< SignalingService::Stub> SignalingService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SignalingService::Stub> stub(new SignalingService::Stub(channel, options));
  return stub;
}

SignalingService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_MessageCall_(SignalingService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::signaling::Message, ::signaling::Message>* SignalingService::Stub::MessageCallRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::signaling::Message, ::signaling::Message>::Create(channel_.get(), rpcmethod_MessageCall_, context);
}

void SignalingService::Stub::async::MessageCall(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::signaling::Message,::signaling::Message>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::signaling::Message,::signaling::Message>::Create(stub_->channel_.get(), stub_->rpcmethod_MessageCall_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::signaling::Message, ::signaling::Message>* SignalingService::Stub::AsyncMessageCallRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::signaling::Message, ::signaling::Message>::Create(channel_.get(), cq, rpcmethod_MessageCall_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::signaling::Message, ::signaling::Message>* SignalingService::Stub::PrepareAsyncMessageCallRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::signaling::Message, ::signaling::Message>::Create(channel_.get(), cq, rpcmethod_MessageCall_, context, false, nullptr);
}

SignalingService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SignalingService_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< SignalingService::Service, ::signaling::Message, ::signaling::Message>(
          [](SignalingService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::signaling::Message,
             ::signaling::Message>* stream) {
               return service->MessageCall(ctx, stream);
             }, this)));
}

SignalingService::Service::~Service() {
}

::grpc::Status SignalingService::Service::MessageCall(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::signaling::Message, ::signaling::Message>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace signaling

